from __future__ import annotations


DEFAULT_LMSTUDIO_BASE_URL = "http://localhost:1234/v1"
DEFAULT_LMSTUDIO_MODEL = "infinity-parser2-flash"
DEFAULT_LMSTUDIO_TIMEOUT_SECONDS = 900.0
DEFAULT_LMSTUDIO_CONTEXT_TOKENS = 262_144
DEFAULT_LMSTUDIO_TEMPERATURE = 0.0
DEFAULT_LMSTUDIO_REPEAT_PENALTY = 1.2
