services:
  otel-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: trapo-otel-lgtm
    ports:
      - "3000:3000"
      - "3200:3200"
      - "4040:4040"
      - "4317:4317"
      - "4318:4318"
      - "9090:9090"
    environment:
      GF_PATHS_DATA: /data/grafana
      CONTAINER_RUNTIME: docker
    volumes:
      - trapo-otel-grafana:/data/grafana
      - trapo-otel-prometheus:/data/prometheus
      - trapo-otel-loki:/data/loki
      - trapo-otel-tempo:/data/tempo
      - trapo-otel-pyroscope:/data/pyroscope
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/ready"]
      interval: 10s
      timeout: 5s
      retries: 30

volumes:
  trapo-otel-grafana:
  trapo-otel-prometheus:
  trapo-otel-loki:
  trapo-otel-tempo:
  trapo-otel-pyroscope:
